# Generated by Django 4.2.11 on 2024-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingdata',
            name='hotel_number_of_reviews',
            field=models.CharField(blank=True, null=True),
        ),
    ]
