# Generated by Django 4.2.11 on 2024-04-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_alter_scrapingdata_hotel_number_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingdata',
            name='hotel_number_of_reviews',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
